server:
  port: 8761
spring:
  profiles: peer2
eureka:
  instance:
    hostname: peer2 # 设置该实例的主机地址
    instance-id: ${spring.cloud.client.ip-address}:${server.port} # 修改该实例的微服务名为：IP:端口
    lease-renewal-interval-in-seconds: 10 # 该实例的发送心跳到eureka服务端的间隔时间
    lease-expiration-duration-in-seconds: 30 # 指示eureka服务端等待该实例下一次心跳的超时时间
  client:
    # 向其它eureka服务器上注册自己的信息
    register-with-eureka: false
    # 获取其它eureka服务器注册表上的注册信息
    fetch-registry: false
    service-url: 
       # 设置其它eureka server节点的地址
       defaultZone: http://peer1:8091/eureka/